# Generated by Django 4.0 on 2025-04-05 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название лекции')),
                ('content', models.TextField(verbose_name='Содержание лекции')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lectures/images/', verbose_name='Изображение')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineschoolapp.course', verbose_name='Курс')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineschoolapp.teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='onlineschoolapp.lecture', verbose_name='Лекция')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineschoolapp.teacher', verbose_name='Преподаватель')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст вопроса')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Правильный ответ')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='onlineschoolapp.quiz', verbose_name='Тест')),
            ],
        ),
    ]
