# Generated by Django 4.0 on 2025-04-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschoolapp', '0002_lecture_quiz_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Правильный текстовый ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='matching_pairs',
            field=models.JSONField(blank=True, null=True, verbose_name='Пары для соответствия'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый ответ'), ('single_choice', 'Выбор одного варианта'), ('multiple_choice', 'Выбор нескольких вариантов'), ('matching', 'Установление соответствия')], default=1, max_length=20, verbose_name='Тип вопроса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный вариант')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='onlineschoolapp.question')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('matching_answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineschoolapp.question')),
                ('selected_choices', models.ManyToManyField(blank=True, to='onlineschoolapp.Choice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='onlineschoolapp.student')),
            ],
            options={
                'unique_together': {('student', 'question')},
            },
        ),
    ]
