# Generated by Django 4.0 on 2025-04-06 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschoolapp', '0003_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineschoolapp.course'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lectures/'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlineschoolapp.teacher'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
