# Generated by Django 4.0 on 2025-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineschoolapp', '0004_lecture_created_at_alter_lecture_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='audio',
            field=models.FileField(blank=True, help_text='Загрузите аудиофайл', null=True, upload_to='lectures/audio/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, help_text='Загрузите видеофайл', null=True, upload_to='lectures/videos/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Или вставьте ссылку на YouTube', null=True),
        ),
    ]
